version: "3.8"
services:
  eureka:
    restart: always
    container_name: eureka
    hostname: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports: 
      - "8761:8761"
    networks:
      - racunovodstvo

  gateway:
    hostname: gateway
    restart: always
    ports:
      - "8080:8080"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_ORIGINS: http://localhost:4200
      REGISTRY_HOST: eureka
    networks:
      - racunovodstvo
    depends_on:
      - eureka

  mysql_db:
    image: mysql:8.0.28
    hostname: mysql_db
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init-db.sql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_NAME
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init-db.sql:/data/application/init-db.sql
    networks:
      - racunovodstvo

  user_service:
    hostname: user
    container_name: user
    restart: unless-stopped
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      REGISTRY_HOST: eureka
    ports:
      - "8082:8080"
    networks:
      - racunovodstvo
    depends_on:
      - mysql_db
      - eureka

  knjizenje_service:
    hostname: knjizenje
    restart: unless-stopped
    build:
      context: ./knjizenje
      dockerfile: Dockerfile
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: mysql_db
      REGISTRY_HOST: eureka
    ports:
      - "8081:8080"
    networks:
      - racunovodstvo
    depends_on:
      - mysql_db
      - eureka

  preduzece_service:
    hostname: preduzece
    restart: unless-stopped
    build:
      context: ./preduzece
      dockerfile: Dockerfile
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: mysql_db
      REGISTRY_HOST: eureka
    ports:
      - "8083:8080"
    networks:
      - racunovodstvo
    depends_on:
      - mysql_db
      - eureka

  front:
    restart: always
    build:
      context: ../Racunovodstvo-Front
      dockerfile: Dockerfile
    ports: 
      - "4200:80"
    networks:
      - racunovodstvo

volumes:
  db:
    driver: local

networks:
  racunovodstvo:
    name: racunovodstvo
