version: "3.8"
services:
  eureka:
    image: ghcr.io/raf-si-2021/racunovodstvo-eureka:latest
    build: ./eureka
    restart: always
    container_name: eureka
    hostname: eureka
    ports:
      - "8761:8761"
    networks:
      - racunovodstvo

  gateway:
    image: ghcr.io/raf-si-2021/racunovodstvo-gateway:latest
    build: ./gateway
    hostname: gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_ORIGINS: http://localhost:4200
      REGISTRY_HOST: eureka
    networks:
      - racunovodstvo
    depends_on:
      - eureka

  mysql_db:
    image: docker.io/bitnami/mysql:8.0
    hostname: mysql_db
    container_name: mysql_db
    env_file: .env
    ports:
      - '3306'
    volumes:
      - db:/bitnami/mysql/data
    environment:
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: $MYSQL_REPLICATION_PASSWORD
      MYSQL_DATABASE: $MYSQL_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    networks:
      - racunovodstvo

  mysql_slave:
    image: docker.io/bitnami/mysql:8.0
    hostname: mysql_slave
    container_name: mysql_slave
    env_file: .env
    ports:
      - '3306'
    depends_on:
      - mysql_db
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: $MYSQL_REPLICATION_PASSWORD
      MYSQL_DATABASE: $MYSQL_NAME
      MYSQL_MASTER_HOST: mysql_db
      MYSQL_MASTER_PORT_NUMBER: 3306
      MYSQL_MASTER_ROOT_PASSWORD: $MYSQL_PASSWORD
    networks:
      - racunovodstvo

  user_service:
    image: ghcr.io/raf-si-2021/racunovodstvo-user:latest
    build: ./user
    hostname: user
    container_name: user
    restart: unless-stopped
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      REGISTRY_HOST: eureka
    ports:
      - "8082:8080"
    networks:
      - racunovodstvo
    depends_on:
      - mysql_db
      - eureka
      - gateway

  knjizenje_service:
    image: ghcr.io/raf-si-2021/racunovodstvo-knjizenje:latest
    build: ./knjizenje
    hostname: knjizenje
    restart: unless-stopped
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: mysql_db
      REGISTRY_HOST: eureka
    ports:
      - "8081:8080"
    networks:
      - racunovodstvo
    depends_on:
      - mysql_db
      - eureka
      - gateway

  preduzece_service:
    image: ghcr.io/raf-si-2021/racunovodstvo-preduzece:latest
    build: ./preduzece
    hostname: preduzece
    restart: unless-stopped
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: mysql_db
      REGISTRY_HOST: eureka
    ports:
      - "8083:8080"
    networks:
      - racunovodstvo
    depends_on:
      - mysql_db
      - eureka
      - gateway

  front:
    image: ghcr.io/raf-si-2021/racunovodstvo-front:latest
    restart: always
    ports:
      - "4200:80"
    networks:
      - racunovodstvo

volumes:
  db:
    driver: local

networks:
  racunovodstvo:
    name: racunovodstvo
